import { Shield, Zap, Brain, Lock, Activity, Database, MessageSquare } from "lucide-react"

export const features = [
    {
        icon: Shield,
        title: "Incident Reporting with Evidence Upload",
        description: "Victims can file reports and attach documents, images, or videos for investigation.",
        details: [
            "Allows users to securely report cyber incidents",
            "Supports uploads of photos, videos, and documents as evidence",
            "Ensures confidentiality and protection of submitted data",
            "Tracks case progress and updates victims in real-time",
            "Integrates with law enforcement systems for streamlined handling",
        ],
        color: "from-blue-500/20 to-cyan-500/20",
    },
    {
        icon: Zap,
        title: "Awareness Hub for Educational Content",
        description: "Provides articles, guides, and safety tips to promote digital literacy.",
        details: [
            "Regularly updated cybersecurity awareness articles",
            "Step-by-step safety guides for online protection",
            "Interactive infographics and videos for learning",
            "Content curated by cybersecurity experts",
            "Encourages safe digital behavior and prevention practices",
        ],
        color: "from-purple-500/20 to-pink-500/20",
    },
    {
        icon: Brain,
        title: "Role-Based Dashboards",
        description: "Customized interfaces for victims, investigators, and admins to view relevant data and tasks.",
        details: [
            "Victims can monitor their reports and receive status updates",
            "Investigators access case files and evidence efficiently",
            "Admins manage users, permissions, and overall platform activity",
            "Personalized views enhance workflow efficiency",
            "Ensures secure access control for each role",
        ],
        color: "from-orange-500/20 to-red-500/20",
    },
    {
        icon: Lock,
        title: "Crime Mapping and Statistics",
        description: "Visualizes incident locations and trends for better situational awareness.",
        details: [
            "Interactive maps show real-time crime locations",
            "Trend analysis of cyber incidents by type and region",
            "Heatmaps help identify recurring threats and hotspots",
            "Supports predictive analysis for proactive measures",
            "Aids law enforcement and researchers in data-driven decisions",
        ],
        color: "from-green-500/20 to-emerald-500/20",
    },
    {
        icon: Activity,
        title: "Notification System",
        description: "Sends real-time alerts when case statuses change or new updates are published.",
        details: [
            "Instant notifications for victims and investigators",
            "Email and in-app alerts for case progress updates",
            "Customizable notification preferences per user",
            "Keeps all stakeholders informed and engaged",
            "Integrates seamlessly with dashboards and reports",
        ],
        color: "from-indigo-500/20 to-blue-500/20",
    },
    {
        icon: Database,
        title: "Responsive UI with React & JavaScript",
        description: "Ensures smooth, accessible, and visually appealing experience across all devices.",
        details: [
            "Modern, mobile-first responsive design",
            "Optimized for accessibility and performance",
            "Built using React and JavaScript for dynamic rendering",
            "Lightweight components ensure fast load times",
            "Provides a consistent experience on all screen sizes",
        ],
        color: "from-yellow-500/20 to-orange-500/20",
    },
    {
        icon: MessageSquare,
        title: "Messaging Service",
        description: "Provides user-friendly chat between users for communication and support.",
        details: [
            "Real-time messaging between victims and investigators",
            "Supports attachments and secure message storage",
            "End-to-end encryption for all chat data",
            "Notification alerts for new messages",
            "Simplifies communication and improves case handling speed",
        ],
        color: "from-pink-500/20 to-rose-500/20",
    },
]