# Generated by Django 5.2.6 on 2025-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAssignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'incident_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
    ]
