# Generated by Django 5.2.6 on 2025-09-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awareness', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awareness.crimetypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.investigators')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.incidents')),
            ],
            options={
                'db_table': 'incident_assignments',
            },
        ),
    ]
