# Generated by Django 5.2.6 on 2025-09-20 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awareness', '0001_initial'),
        ('incidents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentassignments',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.investigators'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='crime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awareness.crimetypes'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentassignments',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.incidents'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.locations'),
        ),
    ]
