# Generated by Django 5.2.6 on 2025-09-24 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incidentassignments',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='incidentassignments',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='incidentassignments',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='crime_type',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='incident_id',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='title',
        ),
        migrations.AddField(
            model_name='incidentassignments',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentassignments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidents'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='incidentassignments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='incidents',
            table=None,
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
