# Generated by Django 5.2.6 on 2025-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incidents_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
