# Generated by Django 5.2.6 on 2025-09-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
        ('incidents', '0004_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentassignments',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='incidents',
            name='crime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awareness.crimetypes'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.locations'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='in_progress', max_length=20),
        ),
        migrations.AlterModelTable(
            name='incidents',
            table='incidents',
        ),
    ]
