# Generated by Django 5.2.6 on 2025-10-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentassignments_status_incidents_crime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentassignments',
            name='status',
        ),
    ]
