# Generated by Django 5.2.6 on 2025-10-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_remove_incidentassignments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
