# Generated by Django 5.2.6 on 2025-10-18 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_incidentassignments_assigned_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentassignments',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 10, 11, 40, 367977, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 10, 11, 40, 368011, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
