# Generated by Django 5.2.6 on 2025-10-19 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incidentassignments_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 8, 42, 5, 687813, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 8, 42, 5, 687813, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
