# Generated by Django 5.2.6 on 2025-10-19 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_alter_incidentassignments_assigned_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 10, 53, 34, 345646, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 10, 53, 34, 345619, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
