<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-19 13:53
=======
# Generated by Django 5.2.6 on 2025-10-19 17:17
>>>>>>> 26b22df63342ec9da0a57e55962b481398c1442e

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_alter_incidentassignments_assigned_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_deadline',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 13, 53, 0, 638113, tzinfo=datetime.timezone.utc), null=True),
=======
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 17, 17, 12, 631058, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 26b22df63342ec9da0a57e55962b481398c1442e
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='resolved_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 13, 53, 0, 638097, tzinfo=datetime.timezone.utc), null=True),
=======
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 17, 17, 12, 631058, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 26b22df63342ec9da0a57e55962b481398c1442e
        ),
    ]
