# Generated by Django 5.2.6 on 2025-10-20 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_alter_incidentassignments_assigned_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentassignments',
            name='assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 10, 49, 54, 885206, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='incidentassignments',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 10, 49, 54, 885171, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
