# Generated by Django 5.2.6 on 2025-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeTypes',
            fields=[
                ('crime_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'crime_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solutions_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_actions', models.TextField(blank=True, null=True)),
                ('awareness_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'solutions',
                'managed': False,
            },
        ),
    ]
