# Generated by Django 5.2.6 on 2025-09-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeTypes',
            fields=[
                ('crime_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'crime_types',
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solutions_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_actions', models.TextField(blank=True, null=True)),
                ('awareness_level', models.CharField(blank=True, max_length=50, null=True)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awareness.crimetypes')),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
    ]
