# Generated by Django 5.2.6 on 2025-10-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_awarenessresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'flairs',
            },
        ),
        migrations.AlterModelTable(
            name='awarenessresource',
            table='awareness_resources',
        ),
        migrations.AddField(
            model_name='awarenessresource',
            name='flair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='awareness.flair'),
        ),
    ]
