# Generated by Django 5.2.6 on 2025-10-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0003_flair_alter_awarenessresource_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimetypes',
            name='crime_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
