# Generated by Django 5.2.6 on 2025-10-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0004_alter_crimetypes_crime_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='crime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awareness.crimetypes'),
        ),
    ]
