# Generated by Django 5.2.6 on 2025-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0005_alter_solutions_crime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenessresource',
            name='flair',
        ),
        migrations.AddField(
            model_name='awarenessresource',
            name='flair',
            field=models.ManyToManyField(blank=True, related_name='resources', to='awareness.flair'),
        ),
    ]
