# Generated by Django 5.2.6 on 2025-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='broadcast_type',
            field=models.CharField(blank=True, choices=[('all', 'All Users'), ('investigators', 'All Investigators'), ('victims', 'All Victims')], max_length=20, null=True),
        ),
    ]
