# Generated by Django 5.2.6 on 2025-10-02 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_initial'),
        ('incidents', '0005_incidentassignments_status_incidents_crime_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='file_path',
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidences/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='incidents.incidents'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='submitted_by',
            field=models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
