# Generated by Django 5.2.6 on 2025-10-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_remove_evidence_file_path_evidence_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='title',
            field=models.CharField(default='Evidence File <django.db.models.fields.AutoField>', max_length=255),
        ),
    ]
