# Generated by Django 5.2.6 on 2025-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_evidence_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
