# Generated by Django 5.2.6 on 2025-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('target_table', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_log',
                'managed': False,
            },
        ),
    ]
