# Generated by Django 5.2.6 on 2025-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_id',
            field=models.AutoField(db_column='log_id', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='log_id',
            new_name='id',
        ),
    ]
